server:
  port: 8090

spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
    past-due-cron: '* * */24 * * *'
  mvc:
    servlet:
      path: /apis/todo-service

  datasource:
    url: jdbc:h2:mem:todoDB
    username: password
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, trace, docs, mappings

page:
  size: 20
